export const LABEL = {
  ADDED: 'Added',
  ADD_TO_OVERVIEW: 'Add to overview',
  EVERYTHING: 'Everything',
  SHARED_WITH_ME: 'Shared with me',
  CREATE_SPACE: 'Create space',
  SPACES: 'Spaces',
  NO_ASSIGNEES_SELECTED: 'No Assignees selected',
  SECONDS_TO_SIGN_UP: 'Seconds to sign up!',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
  ALREADY_A_MEMBER: 'Already a member?',
  DONT_HAVE_AN_ACCOUNT: 'Don\'t have an account ?',
  VERIFY_YOUR_EMAIL: 'Verify your email',
  SENDING: 'Sending...',
  LOGIN: 'Login',
  SIGN_UP: 'Sign Up',
  RESENDING_CODE: 'Resend code',
  VERIFY: 'Verify',
  WE_JUST_EMAILED_YOU: 'We just emailed you.',
  PLEASE_ENTER_THE_CODE_WE_JUST_EMAILED_YOU:'Please enter the code we emailed you',
  CONFIRMATION_CODE: 'Confirmation code'
};
