export const LABEL = {
  TEAM_TREKKING: 'Team Trekking',
  ADDED: 'Added',
  ADD: 'Add',
  ADD_TO_OVERVIEW: 'Add to overview',
  EVERYTHING: 'Everything',
  SHARED_WITH_ME: 'Shared with me',
  CREATE_SPACE: 'Create space',
  SPACES: 'Spaces',
  NO_ASSIGNEES_SELECTED: 'No Assignees selected',
  DESTRUCTIVE: 'destructive',
  LOW: 'Low',
  NORMAL: 'Normal',
  HIGH: 'High',
  URGENT: 'Urgent',
  TASKS_SELECTED: 'Tasks selected',
  ESC: 'ESC',
  DESELECT_ALL: 'Deselect all',
  WHAT_WILL_YOU_USE_THIS_WORKSPACE_FOR: 'What will you use this workspace for?',
  WHAT_WOULD_YOU_LIKE_TO_MANAGE: 'What would you like to manage?',
  INVITE_PEOPLE_TO_YOUR_WORKSPACE: 'Invite people to your workspace',
  HOW_DID_YOU_HEAR_ABOUT_THIS: 'How did you hear about this?',
  DO_YOU_USE_ANY_OF_THESE_TOOLS: 'Do you use any of these tools?',
  WHICH_TOOLS_WOULD_YOU_LIKE_TO_INTEGRATE:
    'Which tools would you like to integrate?',
  WHICH_FEATURES_ARE_YOU_INTERESTED_IN: 'Which features are you interested in?',
  LASTLY_WHAT_WOULD_YOU_LIKE_TO_NAME_YOUR_WORKSPACE:
    'Lastly, what would you like to name your workspace?',
  ENTER_EMAIL_ADDRESSES_ONBOARDING: 'Enter email addresses',
  INVITE_PEOPLE_TO_YOUR_WORKSPACE_: 'Invite people to your Workspace',
  JAWAHIIRS_WORKSPACE: "Jawahiir's Workspace",
  LOADING: 'Loading...',
  PREARING_TEAM_TREKKING_FOR_YOU: 'Preparing Team Trekking for you',
  SECONDS_TO_SIGN_UP: 'Seconds to sign up!',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
  ALREADY_A_MEMBER: 'Already a member?',
  DONT_HAVE_AN_ACCOUNT: "Don't have an account ?",
  FORGOT_YOUR_PASSWORD: 'Forgot your password?',
  VERIFY_YOUR_EMAIL: 'Verify your email',
  SEND: 'Send',
  SENDING: 'Sending...',
  LOGIN: 'Login',
  SIGN_UP: 'Sign Up',
  SEND_VERIFICATION_CODE: 'Send verification code',
  FAILED_TO_SEND_VERIFICATION_CODE: 'Failed to resend verification code',
  RESENDING_CODE: 'Resend code',
  VERIFY: 'Verify',
  WE_JUST_EMAILED_YOU: 'We just emailed you.',
  PLEASE_ENTER_THE_CODE_WE_JUST_EMAILED_YOU:
    'Please enter the code we emailed you',
  CONFIRMATION_CODE: 'Confirmation code',
  COLLAPSED: 'Collapsed',
  DUPLICATE: 'Duplicate',
  CANCEL: 'Cancel',
  WHAT_WOULD_YOU_LIKE_TO_COPY: 'What would you like to copy?',
  CUSTOMIZE: 'Customize',
  ALL_COMMENTS_FIELDS_AND_SETTINGS_WILL_BE_DUPLICATED_EXACTLY_AS_IS:
    'All comments, fields, and settings will be duplicated exactly as is.',
  CHOOSE_SPECIFIC_ELEMENTS_TO_COPY_FROM_THE_ORIGINAL_TASK:
    'Choose specific elements to copy from the original task.',
  INCLUDE_THE_FULL_HISTORY_AND_ACTIVITY_ON_THE_TASK_IN_THE_NEW_TASK:
    'Include the full history and activity on the task in the new task.',
  NOTIFY_TEAM_MEMBERS_ABOUT_THE_NEW_DUPLICATED_TASK:
    'Notify team members about the new duplicated task.',
  SEND_NOTIFICATIONS: 'Send notifications',
  NEW_TASK_NAME: 'New task name',
  DUPLICATE_TASK: 'Duplicate task',
  WHERE_SHOULD_THIS_TASK_BE_CREATED: 'Where should this task be created?',
  FINAL_INITIATIVE: 'Final-Initiative',
  SEARCH_OR_CREATE_NEW: 'Search or create new',
  CLEAR: 'Clear',
  SETTINGS: 'Settings',
  UPGRADE: 'Upgrade',
  MANAGE_USERS: 'Manage Users',
  APP_CENTER: 'App Center',
  TEMPLATE_CENTER: 'Template Center',
  CUSTOM_FIELD_MANAGER: 'Custom Field Manager',
  AUTOMATIONS_MANAGER: 'Automations Manager',
  SWITCH_WORKSPACE: 'Switch Workspace',
  MEMBERS: 'Members',
  CREATE_WORKSPACE: 'Create Workspace',
  MANAGE_SPACES: 'Manage Spaces',
  EXPAND_ALL_FOLDERS: 'Expand all Folders',
  SHOW_ALL_SPACES: 'Show all Spaces',
  SHOW_ARCHIVED: 'Show archived',
  RENAME: 'Rename',
  COPY_LINK: 'Copy link',
  CREATE_NEW: 'Create new',
  PAGE: 'Page',
  DATABASE: 'Database',
  BOARD: 'Board',
  FOLDER_SETTINGS: 'Folder settings',
  GENERAL: 'General',
  PERMISSIONS: 'Permissions',
  EXPORT: 'Export',
  TEMPLATES: 'Templates',
  CREATE_TEMPLATE: 'Create Template',
  BROWSE_TEMPLATES: 'Browse Templates',
  MY_TEMPLATES: 'My Templates',
  ADD_TO_FAVORITES: 'Add to Favorites',
  MOVE: 'Move',
  TO_WORKSPACE: 'To Workspace',
  TO_FOLDER: 'To Folder',
  ARCHIVE: 'Archive',
  DELETE: 'Delete',
  SHARING_AND_PERMISSIONS: 'Sharing & Permissions',
  LIST: 'List',
  TASK: 'Task',
  TASKS: 'Tasks',
  SUBTASK: 'Subtask',
  CONVERT_LIST_TO_SPRINT: 'Convert List to Sprint',
  COLOR_AND_ICON: 'Color & Icon',
  CHANGE_ICON: 'Change Icon',
  CHANGE_COLOR: 'Change Color',
  LIST_SETTINGS: 'List settings',
  LIST_INFO: 'List Info',
  DEFAULT_TASK_TYPE: 'Default task type',
  BUG: 'Bug',
  FEATURE: 'Feature',
  EMAIL_TO_LIST: 'Email to List',
  COLLAPSE_GROUP: 'Collapse group',
  ARCHIVE_ALL_IN_THIS_GROUP: 'Archive All in this group',
  SELECT_ALL: 'Select all',
  EDIT_STATUSES: 'Edit Statuses',
  ADD_TO: 'Add to',
  CONVERT_TO: 'Convert to',
  CONVERT_TO_LIST: 'List',
  TASK_TYPE: 'Task Type',
  REMIND_ME: 'Remind Me',
  SEND_EMAIL_TO_TASK: 'Send email to task',
  MERGE: 'Merge',
  DEPENDENCIES: 'Dependencies',
  SAVE_AS_TEMPLATE: 'Save as Template',
  UPDATE_EXISTING_TEMPLATE: 'Update existing Template',
  TOGGLE_TEMPATES_DIALOG: 'Browse Templates',
  DEFAULT_SET: 'Default Set',
  ARCHIVE_ALL_IN_GROUP: 'Archive All in this group',
  MILESTONE: 'Milestone',
  FORM_RESPONSE: 'Form Response',
  SEARCH_STATUSES: 'Search...',
  NO_STATUS_FOUND_MATCHING: ' No status found matching',
  SPRINT_BACKLOG: 'SPRINT BACKLOG',
  STARTING: 'STARTING',
  IN_PROGRESS: 'IN PROGRESS',
  COMPLETED: 'COMPLETED',
  IN_REVIEW: 'IN REVIEW',
  REJECTED: 'REJECTED',
  BLOCKED: 'BLOCKED',
  CHANGES_ARE_AUTOMATICALLY_SAVED: ' Changes are automatically saved',
  TIME_ESTIMATE: 'Time Estimate',
  TOTAL_WITH_SUBTASKS: ' TOTAL WITH SUBTASKS',
  COPY_LINK_SHORT: 'Copy Link',
  COPY_ID: 'Copy Id',
  NEW_TAB: 'New Tab',
  ADD_COLUMN: 'Add a column',
  ANOTHER_LIST: 'Another List',
  FAVORITES: 'Favorites',
  PERSONAL_LIST: 'Personal List',
  LINEUP: 'LineUp',
  TRAY: 'Tray',
  NOTIFY_ME_ON_ALL_ACTIVITY_FOR_THIS_TASK:
    'Notify me on all activity for this task.',
  NOTIFY_ME_ONLY_ON_MENTIONS_OR_ASSIGNMENT:
    'Notify me only on @mentions or assignment.',
  NO_WATCHERS_FOUND_MATCHING: 'No watchers found matching',
  NO_WATCHERS_YET: 'No watchers yet',
  YOU: 'You',
  UN_WATCH: 'Unwatch',
  SEARCH_WATCHER: 'Search Watchers...',
  BACK: 'Back',
  NEXT: 'Next',
  FINISH: 'Finish',
  TRY_THE_NAME_OF_YOUR_ORGANIZATION: 'Try the name of your organization',
  DONT_WORRY_YOU_WILL_HAVE_ACCESS:
    "Don't worry, you'll have access to all your data",
  NO_COMPLTED_TASKS: 'No completed tasks',
  TODO: 'To Do',
  DONE: 'Done',
  NO_TASKS: 'No tasks',
  HOME: 'Home',
  MANAGE_CARDS: 'Manage cards',
  ADD_CARDS: 'Add Cards',
  DESCRIPTION: 'Description',
  WATCH: 'Watch',
  SUGGEST_SUBTASKS: 'Suggest subtasks',
  ACTIVITIES: 'Activities',
  UNSELECT_ALL: 'Unselect All',
  APPLY_FILTERS: 'Apply Filters',
  SORT: 'Sort',
  FULL_SCREEN: 'Full Screen',
  CHECKLISTS: 'Checklists',
  ATTACHMENTS: 'Attachments',
  EDIT_CHECKLIST: 'Edit Checklist',
  DELETE_CHECKLIST: 'Delete Checklist',
  TRY_ADJUSTING_YOUR_SEARCH_TERMS: 'Try adjusting your search terms',
  NO_ACTIVITIES_FOUND: 'No activities found',
  SEARCH: 'Search...',
  FOLDER: 'Folder',
  COLOR_ICON: 'Color & Icon',
  SPACE_SETTINGS: 'Space settings',
  HIDE_SPACE: 'Hide Space',
  BACK_TO_WORKSPACE: 'Back to workspace',
  WORKSPACE: 'Workspace',
  WORKSPACE_SETTINGS: 'Workspace Settings',
  WORKSPACE_NAME: 'Workspace name',
  WHITE_LABEL: 'White Label',
  SKIN_TEAM_TREKKING:
    'Skin TeamTrekking with your brand colors, logo, and a custom URL.',
  PERSONAL_WORKSPACE_LAYOUT: 'Personal Workspace Layout',
  TIME_TO_COLLABORATE:
    'Time to collaborate? Turn this off to show all features designed for team productivity.',
  DELETE_WORKSPACE: 'Delete Workspace',
  SAVED: 'Saved',
  SAVE: 'Save',
  WORKSPACE_COLOR: 'Workspace color',
  ADD_CUSTOM_COLOR: 'Add custom avatar',
  WATCH_THESE_VIDEOS:
    'Watch these quick videos to know how Team Trekking can transform your productivity.',
  REQUIRED_VIEWS: 'Required Views',
  DEFAULT_VIEW_TEMPLATES: 'Default View Templates',
  DEFAULT_SETTINGS_FOR_VIEWS: 'Default settings for Views',
  ALWAYS_REQUIRED: 'ALWAYS REQUIRED',
  DEFAULT_VIEW: 'Default View',
  DEFAULT_VIEWS: 'Default Views',
  EDIT_SPACE_SETTINGS: 'Edit Space settings',
  REQUIRED_VIEWS_DESCRIPTION:
    'When navigating to Spaces, Folders, and Lists in ClickUp, you can set which view(s) are automatically created and required, without having to create them manually. These views cannot be deleted.',
  DEFINE_YOUR_WORKFLOW: 'Define your workflow',
  DEFINE_WORKFLOW_DESCRIPTION:
    'Choose a pre-configured solution or customize to your liking with advanced ClickApps, required views, and task statuses.',
  SPACE_DESCRIPTION:
    'A Space represents teams, departments, or groups, each with its own Lists, workflows, and settings.',
  ICON_AND_NAME: 'Icon & Name',
  SPACE_NAME: 'My New Space',
  OPTIONAL: 'optional',
  MAKE_PRIVATE: 'Make Private',
  ONLY_YOU_AND_INVITED_HAVE_ACCESS: 'Only you and invited members have access',
  NO_INVITED_USERS: 'No invited Users',
  SELECT_USERS: 'Select Users',
  OWNER: 'Owner',
  PLEASE_SELECT_OWNER: 'Please select an Owner',
  USERS: 'Users',
  SAVE_CHANGES: 'Save Changes',
  PROJECTX_MOON: 'ProjecX Moon',
  DEFAULT_INITIAL: 'P',
  EDIT_SPACE_STATUS: 'Edit Space Status',
  STATUS_TEMPLATE: 'Status template',
  SAVE_TEMPLATE: 'Save Template',
  MY_SETTINGS: 'My Settings',
  PROFILE: 'Profile',
  YOUR_PERSONAL_INFORMATION_AND_ACCOUNT_SECURITY:
    'Your personal information and account security settings.',
  AVATAR: 'Avatar',
  FULL_NAME: 'Full Name',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  PEOPLE: 'People',
  WORKSPACES: 'Workspaces',
  NOTIFICATIONS: 'Notications',
  REFERALS: 'Referrals',
  WARNING: 'Warning',
  DELETING_THIS_WORKSPACE_WILL_DELETE_ALL_FILES:
    'Deleting this Workspace will delete all files, tasks, and history. This action is permanent and cannot be reverted. To continue, please type Workspace name to delete.',
  ALSO_PERMANENTLY_DELETE_ALL_THIRD_PARTY_DATA:
    'Also permanently delete all third-party data and do not follow\n' +
    '                recovery of this Workspace',
  USE_SPACE_STATUSES: 'Use Space statuses',
};
