export const LABEL = {
  ADDED: 'Added',
  ADD_TO_OVERVIEW: 'Add to overview',
  EVERYTHING: 'Everything',
  SHARED_WITH_ME: 'Shared with me',
  CREATE_SPACE: 'Create space',
  SPACES: 'Spaces',
  NO_ASSIGNEES_SELECTED: 'No Assignees selected',
  DESTRUCTIVE: 'destructive',
  LOW: 'Low',
  NORMAL: 'Normal',
  HIGH: 'High',
  URGENT: 'Urgent',
  WHAT_WILL_YOU_USE_THIS_WORKSPACE_FOR: 'What will you use this workspace for?',
  WHAT_WOULD_YOU_LIKE_TO_MANAGE: 'What would you like to manage?',
  INVITE_PEOPLE_TO_YOUR_WORKSPACE: 'Invite people to your workspace',
  DO_YOU_USE_ANY_OF_THESE_TOOLS: 'Do you use any of these tools?',
  WHICH_FEATURES_ARE_YOU_INTERESTED_IN: 'Which features are you interested in?',
  LASTLY_WHAT_WOULD_YOU_LIKE_TO_NAME_YOUR_WORKSPACE:
    'Lastly, what would you like to name your workspace?',
  ENTER_EMAIL_ADDRESSES_ONBOARDING: 'Enter email addresses',
  INVITE_PEOPLE_TO_YOUR_WORKSPACE_: 'Invite people to your Workspace',
  JAWAHIIRS_WORKSPACE: "Jawahiir's Workspace",
  LOADING: 'Loading...',
  PREARING_TEAM_TREKKING_FOR_YOU: 'Preparing Team Trekking for you',
  SECONDS_TO_SIGN_UP: 'Seconds to sign up!',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
  ALREADY_A_MEMBER: 'Already a member?',
  DONT_HAVE_AN_ACCOUNT: "Don't have an account ?",
  FORGOT_YOUR_PASSWORD: 'Forgot your password?',
  VERIFY_YOUR_EMAIL: 'Verify your email',
  SEND: 'Send',
  SENDING: 'Sending...',
  LOGIN: 'Login',
  SIGN_UP: 'Sign Up',
  SEND_VERIFICATION_CODE: 'Send verification code',
  FAILED_TO_SEND_VERIFICATION_CODE: 'Failed to resend verification code',
  RESENDING_CODE: 'Resend code',
  VERIFY: 'Verify',
  WE_JUST_EMAILED_YOU: 'We just emailed you.',
  PLEASE_ENTER_THE_CODE_WE_JUST_EMAILED_YOU: 'Please enter the code we emailed you',
  CONFIRMATION_CODE: 'Confirmation code',
  COLLAPSED: 'Collapsed',
  DUPLICATE: 'Duplicate',
  CANCEL: 'Cancel',
  WHAT_WOULD_YOU_LIKE_TO_COPY: 'What would you like to copy?',
  CUSTOMIZE: 'Customize',
  ALL_COMMENTS_FIELDS_AND_SETTINGS_WILL_BE_DUPLICATED_EXACTLY_AS_IS: 'All comments, fields, and settings will be duplicated exactly as is.',
  CHOOSE_SPECIFIC_ELEMENTS_TO_COPY_FROM_THE_ORIGINAL_TASK: 'Choose specific elements to copy from the original task.',
  INCLUDE_THE_FULL_HISTORY_AND_ACTIVITY_ON_THE_TASK_IN_THE_NEW_TASK: 'Include the full history and activity on the task in the new task.',
  NOTIFY_TEAM_MEMBERS_ABOUT_THE_NEW_DUPLICATED_TASK: 'Notify team members about the new duplicated task.',
  SEND_NOTIFICATIONS: 'Send notifications',
  NEW_TASK_NAME: 'New task name',
  DUPLICATE_TASK: 'Duplicate task',
  WHERE_SHOULD_THIS_TASK_BE_CREATED: 'Where should this task be created?',
  FINAL_INITIATIVE: 'Final-Initiative',
  SEARCH_OR_CREATE_NEW: 'Search or create new',
  CLEAR: 'Clear',
  SETTINGS: 'Settings',
  UPGRADE: 'Upgrade',
  MANAGE_USERS: 'Manage Users',
  APP_CENTER: 'App Center',
  TEMPLATE_CENTER: 'Template Center',
  CUSTOM_FIELD_MANAGER: 'Custom Field Manager',
  AUTOMATIONS_MANAGER: 'Automations Manager',
  SWITCH_WORKSPACE: 'Switch Workspace',
  MEMBERS: 'Members',
  CREATE_WORKSPACE: 'Create Workspace',
  MANAGE_SPACES: 'Manage Spaces',
  EXPAND_ALL_FOLDERS: 'Expand all Folders',
  SHOW_ALL_SPACES: 'Show all Spaces',
  SHOW_ARCHIVED: 'Show archived',
  RENAME: 'Rename',
  COPY_LINK: 'Copy link',
  CREATE_NEW: 'Create new',
  PAGE: 'Page',
  DATABASE: 'Database',
  BOARD: 'Board',
  FOLDER_SETTINGS: 'Folder settings',
  GENERAL: 'General',
  PERMISSIONS: 'Permissions',
  EXPORT: 'Export',
  TEMPLATES: 'Templates',
  CREATE_TEMPLATE: 'Create Template',
  BROWSE_TEMPLATES: 'Browse Templates',
  MY_TEMPLATES: 'My Templates',
  ADD_TO_FAVORITES: 'Add to Favorites',
  MOVE: 'Move',
  TO_WORKSPACE: 'To Workspace',
  TO_FOLDER: 'To Folder',
  ARCHIVE: 'Archive',
  DELETE: 'Delete',
  SHARING_AND_PERMISSIONS: 'Sharing & Permissions',
  LIST: 'List',
  TASK: 'Task',
  SUBTASK: 'Subtask',
  CONVERT_LIST_TO_SPRINT: 'Convert List to Sprint',
  COLOR_AND_ICON: 'Color & Icon',
  CHANGE_ICON: 'Change Icon',
  CHANGE_COLOR: 'Change Color',
  LIST_SETTINGS: 'List settings',
  LIST_INFO: 'List Info',
  DEFAULT_TASK_TYPE: 'Default task type',
  BUG: 'Bug',
  FEATURE: 'Feature',
  EMAIL_TO_LIST: 'Email to List',
  COLLAPSE_GROUP: 'Collapse group',
  ARCHIVE_ALL_IN_THIS_GROUP: 'Archive All in this group',
  SELECT_ALL: 'Select all',
  EDIT_STATUSES: 'Edit Statuses',
  ADD_TO: 'Add to',
  CONVERT_TO: 'Convert to',
  CONVERT_TO_LIST: 'List',
  TASK_TYPE: 'Task Type',
  REMIND_ME: 'Remind Me',
  SEND_EMAIL_TO_TASK: 'Send email to task',
  MERGE: 'Merge',
  DEPENDENCIES: 'Dependencies',
  SAVE_AS_TEMPLATE: 'Save as Template',
  UPDATE_EXISTING_TEMPLATE: 'Update existing Template',
  TOGGLE_TEMPATES_DIALOG: 'Browse Templates',
  DEFAULT_SET: 'Default Set',
  ARCHIVE_ALL_IN_GROUP: 'Archive All in this group',
  MILESTONE: 'Milestone',
  FORM_RESPONSE: 'Form Response',
  MANAGE_SPACES: 'Manage Spaces',
  EXPAND_ALL_FOLDERS: 'Expand all Folders',
  SHOW_ALL_SPACES: 'Show all Spaces',
  SHOW_ARCHIVED: 'Show archived',
  RENAME: 'Rename',
  COPY_LINK: 'Copy link',
  CREATE_NEW: 'Create new',
  PAGE: 'Page',
  DATABASE: 'Database',
  BOARD: 'Board',
  FOLDER_SETTINGS: 'Folder settings',
  GENERAL: 'General',
  PERMISSIONS: 'Permissions',
  EXPORT: 'Export',
  TEMPLATES: 'Templates',
  CREATE_TEMPLATE: 'Create Template',
  BROWSE_TEMPLATES: 'Browse Templates',
  MY_TEMPLATES: 'My Templates',
  ADD_TO_FAVORITES: 'Add to Favorites',
  MOVE: 'Move',
  TO_WORKSPACE: 'To Workspace',
  TO_FOLDER: 'To Folder',
  ARCHIVE: 'Archive',
  DELETE: 'Delete',
  SHARING_AND_PERMISSIONS: 'Sharing & Permissions',
  LIST: 'List',
  TASK: 'Task',
  SUBTASK: 'Subtask',
  CONVERT_LIST_TO_SPRINT: 'Convert List to Sprint',
  COLOR_AND_ICON: 'Color & Icon',
  CHANGE_ICON: 'Change Icon',
  CHANGE_COLOR: 'Change Color',
  LIST_SETTINGS: 'List settings',
  LIST_INFO: 'List Info',
  DEFAULT_TASK_TYPE: 'Default task type',
  BUG: 'Bug',
  FEATURE: 'Feature',
  EMAIL_TO_LIST: 'Email to List',
  COLLAPSE_GROUP: 'Collapse group',
  ARCHIVE_ALL_IN_THIS_GROUP: 'Archive All in this group',
  SELECT_ALL: 'Select all',
  EDIT_STATUSES: 'Edit Statuses',
  ADD_TO: 'Add to',
  CONVERT_TO: 'Convert to',
  CONVERT_TO_LIST: 'List',
  TASK_TYPE: 'Task Type',
  REMIND_ME: 'Remind Me',
  SEND_EMAIL_TO_TASK: 'Send email to task',
  MERGE: 'Merge',
  DEPENDENCIES: 'Dependencies',
  SAVE_AS_TEMPLATE: 'Save as Template',
  UPDATE_EXISTING_TEMPLATE: 'Update existing Template',
  TOGGLE_TEMPATES_DIALOG: 'Browse Templates',
  DEFAULT_SET: 'Default Set',
  ARCHIVE_ALL_IN_GROUP: 'Archive All in this group',
  MILESTONE: 'Milestone',
  FORM_RESPONSE: 'Form Response',
  SEARCH_STATUSES: 'Search statuses...',
  NO_STATUS_FOUND_MATCHING: ' No status found matching',
  SPRINT_BACKLOG: 'SPRINT BACKLOG',
  STARTING: 'STARTING',
  IN_PROGRESS: 'IN PROGRESS',
  COMPLETED: 'COMPLETED',
  IN_REVIEW: 'IN REVIEW',
  REJECTED: 'REJECTED',
  BLOCKED: 'BLOCKED',
};
