export const LABEL = {
  ADDED: 'Added',
  ADD_TO_OVERVIEW: 'Add to overview',
  EVERYTHING: 'Everything',
  SHARED_WITH_ME: 'Shared with me',
  CREATE_SPACE: 'Create space',
  SPACES: 'Spaces',
  NO_ASSIGNEES_SELECTED: 'No Assignees selected',
  DESTRUCTIVE: 'destructive',
  LOW: 'Low',
  NORMAL: 'Normal',
  HIGH: 'High',
  URGENT: 'Urgent',
  WHAT_WILL_YOU_USE_THIS_WORKSPACE_FOR: 'What will you use this workspace for?',
  WHAT_WOULD_YOU_LIKE_TO_MANAGE: 'What would you like to manage?',
  INVITE_PEOPLE_TO_YOUR_WORKSPACE: 'Invite people to your workspace',
  DO_YOU_USE_ANY_OF_THESE_TOOLS: 'Do you use any of these tools?',
  WHICH_FEATURES_ARE_YOU_INTERESTED_IN: 'Which features are you interested in?',
  LASTLY_WHAT_WOULD_YOU_LIKE_TO_NAME_YOUR_WORKSPACE:
    'Lastly, what would you like to name your workspace?',
  ENTER_EMAIL_ADDRESSES_ONBOARDING: 'Enter email addresses',
  INVITE_PEOPLE_TO_YOUR_WORKSPACE_: 'Invite people to your Workspace',
  JAWAHIIRS_WORKSPACE: "Jawahiir's Workspace",
  LOADING: 'Loading...',
  PREARING_TEAM_TREKKING_FOR_YOU: 'Preparing Team Trekking for you',
  SECONDS_TO_SIGN_UP: 'Seconds to sign up!',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
  ALREADY_A_MEMBER: 'Already a member?',
  DONT_HAVE_AN_ACCOUNT: "Don't have an account ?",
  FORGOT_YOUR_PASSWORD: 'Forgot your password?',
  VERIFY_YOUR_EMAIL: 'Verify your email',
  SEND: 'Send',
  SENDING: 'Sending...',
  LOGIN: 'Login',
  SIGN_UP: 'Sign Up',
  SEND_VERIFICATION_CODE: 'Send verification code',
  FAILED_TO_SEND_VERIFICATION_CODE: 'Failed to resend verification code',
  RESENDING_CODE: 'Resend code',
  VERIFY: 'Verify',
  WE_JUST_EMAILED_YOU: 'We just emailed you.',
  PLEASE_ENTER_THE_CODE_WE_JUST_EMAILED_YOU:
    'Please enter the code we emailed you',
  CONFIRMATION_CODE: 'Confirmation code',
  COLLAPSED: 'Collapsed',
};
